In [135]:
import os
import pandas as pd
from pandas.core.common import random_state

In [136]:
""" Machine Learning Foundational Concepts Review

Three Major sections of ML workflow
1. Data -->(Prepare Data for Training)
   1.1. Data Collection
   1.2. Data Loading
   1.3. Data Cleaning
   1.4. Data Exploration and Visualization
   1.5. Feature Engineering: Feature Selection + Feature Transformation
   1.6. Data Splitting : Train-Test-Validation fairly

2. Model:
    2.1. Machine learning Algorithm
    2.2. Artificial Neural Network
    2.3. AI Algorithm i.e. Genetic Algorithm

3. Training
    Hyperparameters tuning i.e. epochs,learning rate, batch size,regularizer etc.
    Optimizer i.e. Gradient Descent Based. Most popular: Adam Optimizer
    Compute Gradient i.e. Gradient Computation Graph
    Update parameters

Overfitting: Models performance very good on training data but poor on
test data
    Reasons: Model is too big/complex than training data
             Or dataset is too small
    Solution: -Regularization in cost function to give penalty to
               restrict gradient descent to perform too well
              -Ensemble Learning i.e. Prediction is done by more than one algorithms
              -Dropout i.e. Removes some connections from the ANN

Underfitting: Models performance is poor on both training and testing data
    Reasons:Model is too simple to capture the underlying data distributions
    Solution:Select more complex model or algorithm

Generalization(Ideal Case): Models performance is well balanced in both training and testing
""";

# DATA

In [137]:
ROOT_DIR="E:\\BongoDev\\Classification_Analysis"
DATA_DIR=os.path.join(ROOT_DIR,"Data")
DATASET_PATH=os.path.join(DATA_DIR,"housing.csv")

dataset=pd.read_csv(DATASET_PATH)
dataset.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [138]:
dataset.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [139]:
numerical_cols=dataset.select_dtypes(include="number").columns
categorical_col=dataset.select_dtypes(include=['object','str']).columns

print(numerical_cols)
print(categorical_col)

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'parking'], dtype='str')
Index(['mainroad', 'guestroom', 'basement', 'hotwaterheating',
       'airconditioning', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [140]:
# Preprocessing

from sklearn.preprocessing import StandardScaler,LabelEncoder
scaler=StandardScaler()
label_encoder=LabelEncoder()

In [141]:
dataset[numerical_cols]=scaler.fit_transform(dataset[numerical_cols])
dataset[numerical_cols]

        price      area  bedrooms  bathrooms   stories   parking
0    4.566365  1.046726  1.403419   1.421812  1.378217  1.517692
1    4.004484  1.757010  1.403419   5.405809  2.532024  2.679409
2    4.004484  2.218232  0.047278   1.421812  0.224410  1.517692
3    3.985755  1.083624  1.403419   1.421812  0.224410  2.679409
4    3.554979  1.046726  1.403419  -0.570187  0.224410  1.517692
..        ...       ...       ...        ...       ...       ...
540 -1.576868 -0.991879 -1.308863  -0.570187 -0.929397  1.517692
541 -1.605149 -1.268613  0.047278  -0.570187 -0.929397 -0.805741
542 -1.614327 -0.705921 -1.308863  -0.570187 -0.929397 -0.805741
543 -1.614327 -1.033389  0.047278  -0.570187 -0.929397 -0.805741
544 -1.614327 -0.599839  0.047278  -0.570187  0.224410 -0.805741

[545 rows x 6 columns]

In [142]:
dataset[categorical_col]=dataset[categorical_col].apply(label_encoder.fit_transform)
dataset.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,4.566365,1.046726,1.403419,1.421812,1.378217,1,0,0,0,1,1.517692,1,0
1,4.004484,1.757010,1.403419,5.405809,2.532024,1,0,0,0,1,2.679409,0,0
2,4.004484,2.218232,0.047278,1.421812,0.224410,1,0,1,0,0,1.517692,1,1
3,3.985755,1.083624,1.403419,1.421812,0.224410,1,0,1,0,1,2.679409,1,0
4,3.554979,1.046726,1.403419,-0.570187,0.224410,1,1,1,0,1,1.517692,0,0

In [143]:
target_var='prefarea'
dataset[target_var].value_counts()

prefarea
0    417
1    128
Name: count, dtype: int64

In [144]:
X=dataset.drop(columns=target_var)
y=dataset[target_var]

X.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,furnishingstatus
0,4.566365,1.046726,1.403419,1.421812,1.378217,1,0,0,0,1,1.517692,0
1,4.004484,1.757010,1.403419,5.405809,2.532024,1,0,0,0,1,2.679409,0
2,4.004484,2.218232,0.047278,1.421812,0.224410,1,0,1,0,0,1.517692,1
3,3.985755,1.083624,1.403419,1.421812,0.224410,1,0,1,0,1,2.679409,0
4,3.554979,1.046726,1.403419,-0.570187,0.224410,1,1,1,0,1,1.517692,0

In [145]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [146]:
y_train.value_counts()

prefarea
0    334
1    102
Name: count, dtype: int64

In [147]:
!pip install imblearn

Requirement already satisfied: imblearn in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (0.0)
Requirement already satisfied: imbalanced-learn in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from imblearn) (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (2.4.3)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (1.17.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (1.8.0)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: C:\Users\HP\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [148]:
from imblearn.over_sampling import SMOTE

smote=SMOTE(random_state=42)
X_train,y_train=smote.fit_resample(X_train,y_train)
y_train.value_counts()

prefarea
0    334
1    334
Name: count, dtype: int64

# MODEL

In [149]:
"""
DECISION TREE
"""
from sklearn.tree import DecisionTreeClassifier
decision_tree=DecisionTreeClassifier(random_state=42)

decision_tree.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [150]:
y_pred=decision_tree.predict(X_test)
print(y_pred)

[0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 1 0 1
 0 0 1 0 1 0 0 1 1 1 1 0 0 1 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1]

In [151]:
from sklearn.metrics import accuracy_score,classification_report

accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

0.7247706422018348

In [152]:
"""
K-NEAREST NEIGHBOUR

example 1 (e1) = [2, 3]
example 2 (e2)
example 3 (e3)
...
example n  (en)

example (e) = [1, 1]

distance(e1, e) = sqrt((2-1)^2+(3-1)^2) = 0.258
distance(e2, e) = sqrt((2-1)^2+(3-1)^2) = 0.356
distance(e3, e) = sqrt((2-1)^2+(3-1)^2) = 0.197
distance(e4, e) = sqrt((2-1)^2+(3-1)^2) = 0.274

k = 3, Closest to e: e1 (1), e3(1), e4(0) prediction = e (1)
""";

In [153]:
from sklearn.neighbors import KNeighborsClassifier

knn_model=KNeighborsClassifier()
knn_model.fit(X_train,y_train)
knn_model.fit(X_train,y_train)
y_pred=knn_model.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
report=classification_report(y_test,y_pred)
print(accuracy)
print(report)

0.6238532110091743
              precision    recall  f1-score   support

           0       0.83      0.64      0.72        83
           1       0.33      0.58      0.42        26

    accuracy                           0.62       109
   macro avg       0.58      0.61      0.57       109
weighted avg       0.71      0.62      0.65       109

In [154]:
"""
Part1: T means correct prediction , F means incorrect prediction
Part2: What is the predicted class
TP:Predicted positive class which are positive
TN:Predicted negative class which are negative
FP:Predicted positive class which infact are negative
FN:Predicted negative class which infact are positive

Accuracy=(TP+TN)/(TP+TN+FP+FN):True predicted class among all classes
Precision=TP/(TP+FP) : Out of all predicted positive classes how many are actually positive
Recall=TP/(TP+FN) : Out of all actual positive classes how many are actually positive
F1=2TP/(2TP+FP+FN): if there are imbalances in the data . then F1 and accuracy will have significant differences
""";

In [155]:
"""
Support Vector Classifier
"""
from sklearn.svm import SVC

svm_model=SVC(probability=True,random_state=42)
svm_model.fit(X_train,y_train)
y_pred=svm_model.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
report=classification_report(y_test,y_pred)
print(f"SVM Classifier Accuracy: {accuracy}")
print("Classification Report:\n",report)

SVM Classifier Accuracy: 0.6697247706422018
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.73      0.77        83
           1       0.35      0.46      0.40        26

    accuracy                           0.67       109
   macro avg       0.58      0.60      0.59       109
weighted avg       0.70      0.67      0.68       109

# ENSEMBLE

In [156]:
""" Boosting
Boosting => Models are trained sequentially

Suppose,
decision_1.fit(X_train, y_train)
decision_2.fit(incorrect_predicted_rows)
decision_3.fit(incorrect_predicted_rows)
"""
from sklearn.ensemble import AdaBoostClassifier

boosting_model=AdaBoostClassifier(
    estimator=DecisionTreeClassifier(random_state=42),
    n_estimators=3,
    random_state=42
)
boosting_model.fit(X_train,y_train)
y_pred=boosting_model.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
report=classification_report(y_test,y_pred)

print(f"Boosting Classifier Accuracy: {accuracy}")
print("Classification Report:\n", report)

Boosting Classifier Accuracy: 0.6880733944954128
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.76      0.79        83
           1       0.38      0.46      0.41        26

    accuracy                           0.69       109
   macro avg       0.60      0.61      0.60       109
weighted avg       0.71      0.69      0.70       109

In [157]:
""" Bagging
Models are learned individually parallely
single decision tree: accuracy: 77%

X_train
y_train

multiple decision tree:
   decision_tree_1.fit(X_train_1, y_train_1)
   decision_tree_2.fit(X_train_2, y_train_2)
   ...
   decision_tree_N.fit(X_train_N, y_train_N)

   predict(x):
      y_pred_1 = decision_tree_1.predict(x)
      y_pred_2 = decision_tree_2.predict(x)
      ...

      return the majority prediction
"""
from sklearn.ensemble import BaggingClassifier

bagging_model=BaggingClassifier(
    estimator=DecisionTreeClassifier(random_state=42),
    n_estimators=10,
    random_state=42
)
bagging_model.fit(X_train,y_train)
y_pred=bagging_model.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
report=classification_report(y_test,y_pred)

print(f"Bagging Classifier Accuracy: {accuracy}")
print("Classification Report:\n", report)

Bagging Classifier Accuracy: 0.7706422018348624
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.88      0.85        83
           1       0.52      0.42      0.47        26

    accuracy                           0.77       109
   macro avg       0.68      0.65      0.66       109
weighted avg       0.76      0.77      0.76       109

In [158]:
"""
Stacking is an ensemble learning technique that combines predictions from multiple base models (of different types) to improve performance.
"""

from sklearn.ensemble import StackingClassifier,RandomForestClassifier

estimators=[
    ('decision_tree',DecisionTreeClassifier(random_state=42)),
    ('knn',KNeighborsClassifier()),
    ('svm',SVC(probability=True,random_state=42)),
]

stacking_model=StackingClassifier(estimators=estimators,final_estimator=RandomForestClassifier(random_state=42),)
stacking_model.fit(X_train,y_train)
y_pred=stacking_model.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
report=classification_report(y_test,y_pred)

print(f"Stacking Classifier Accuracy: {accuracy}")
print("Classification Report:\n", report)

Stacking Classifier Accuracy: 0.6513761467889908
Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.75      0.77        83
           1       0.30      0.35      0.32        26

    accuracy                           0.65       109
   macro avg       0.54      0.55      0.54       109
weighted avg       0.67      0.65      0.66       109

In [159]:
"""
Voting
"""

from sklearn.ensemble import VotingClassifier

voting_model=VotingClassifier(estimators=[
    ('decision_tree',DecisionTreeClassifier(random_state=42)),
    ('knn',KNeighborsClassifier()),
    ('svm',SVC(probability=True,random_state=42)),],
    voting='soft'
)
voting_model.fit(X_train,y_train)
y_pred=voting_model.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
report=classification_report(y_test,y_pred)
print(f"Voting Classifier Accuracy: {accuracy}")
print("Classification Report:\n", report)

Voting Classifier Accuracy: 0.7431192660550459
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.83      0.83        83
           1       0.46      0.46      0.46        26

    accuracy                           0.74       109
   macro avg       0.65      0.65      0.65       109
weighted avg       0.74      0.74      0.74       109