In [1]:
from narwhals.selectors import categorical

"""
Supervised Learning
 -Classification Task: Logistic Regression
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from class_utils.lab_utils_common import dlc,plot_data,draw_vthresh,sigmoid
from class_utils.plt_one_addpt_onclick import plt_one_addpt_onclick
from class_utils.plt_logistic_loss import plt_logistic_cost,plt_two_logistic_loss_curves,plt_simple_example
from class_utils.plt_logistic_loss import soup_bowl,plt_logistic_squared_error

%matplotlib widget
plt.style.use(r"E:\BongoDev\Classification_Analysis\deeplearning.mplstyle")

In [2]:
DATASET_PATH=r"E:\BongoDev\Classification_Analysis\Data\cancer.csv"
cancer_dataset=pd.read_csv(DATASET_PATH)
cancer_dataset.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.0,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.5,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84358402,M,20.29,14.34,135.1,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.2,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN
4,844359,M,18.25,19.98,119.6,1040.0,0.09463,0.10900,0.1127,0.07400,...,27.66,153.2,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368,NaN

In [3]:
cancer_dataset['diagnosis'].value_counts()

diagnosis
B    357
M    116
Name: count, dtype: int64

In [4]:
"""
Classification: Identify the diagnosis given the medical report
"""
cancer_dataset=cancer_dataset[['area_mean','diagnosis']]
cancer_dataset.head()

   area_mean diagnosis
0     1001.0         M
1     1326.0         M
2     1203.0         M
3     1297.0         M
4     1040.0         M

In [5]:
cancer_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 473 entries, 0 to 472
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   area_mean  473 non-null    float64
 1   diagnosis  473 non-null    str
dtypes: float64(1), str(1)
memory usage: 8.0 KB

In [7]:
numerical_cols=cancer_dataset.select_dtypes(include='number').columns
numerical_cols

Index(['area_mean'], dtype='str')

In [9]:
categorical_cols=cancer_dataset.select_dtypes(include=['object','str']).columns
categorical_cols

Index(['diagnosis'], dtype='str')

In [10]:
cancer_dataset[numerical_cols]

     area_mean
0       1001.0
1       1326.0
2       1203.0
3       1297.0
4       1040.0
..         ...
468     1347.0
469     1479.0
470     1261.0
471     1265.0
472      181.0

[473 rows x 1 columns]

In [11]:
cancer_dataset[categorical_cols]

    diagnosis
0           M
1           M
2           M
3           M
4           M
..        ...
468         M
469         M
470         M
471         M
472         B

[473 rows x 1 columns]

In [13]:
# Normalization
min=cancer_dataset[numerical_cols].min()
max=cancer_dataset[numerical_cols].max()
print(min,max)

cancer_dataset[numerical_cols]=(cancer_dataset[numerical_cols]-min)/(max-min)
cancer_dataset.head()

area_mean    143.5
dtype: float64 area_mean    2501.0
dtype: float64

   area_mean diagnosis
0   0.363733         M
1   0.501591         M
2   0.449417         M
3   0.489290         M
4   0.380276         M

In [14]:
# Label Encoding

cancer_dataset[categorical_cols]=cancer_dataset[categorical_cols].apply(
    lambda col:pd.Categorical(col).codes
)
cancer_dataset.head()

   area_mean  diagnosis
0   0.363733          1
1   0.501591          1
2   0.449417          1
3   0.489290          1
4   0.380276          1

In [15]:
print(cancer_dataset['diagnosis'].value_counts())

diagnosis
0    357
1    116
Name: count, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split

train_df,test_df=train_test_split(cancer_dataset,
                                  test_size=0.2,
                                  stratify=cancer_dataset['diagnosis'],
                                  random_state=42)
print(train_df['diagnosis'].value_counts())
print(test_df['diagnosis'].value_counts())

diagnosis
0    285
1     93
Name: count, dtype: int64
diagnosis
0    72
1    23
Name: count, dtype: int64